name: Checks for push

on:
  pull_request:
    branches:
      - main

jobs:
  path-filter:
    outputs:
      actions: ${{steps.changes.outputs.actions}}
      ts: ${{steps.changes.outputs.ts}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            actions:
              - .github/workflows/check.yml
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
              - aqua.yaml
            ts:
              - .github/workflows/check.yml
              - ./**/*.ts
              - deno.jsonc
  check-actions:
    needs: path-filter
    if: needs.path-filter.outputs.actions == 'true'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        if: steps.filter.outputs.actions == 'true'
        with:
          aqua_version: v2.28.1
      - name: Linting
        if: steps.filter.outputs.actions == 'true'
        run: |
          ghalint run
          actionlint
  check-deno:
    needs: path-filter
    if: needs.path-filter.outputs.ts == 'true'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
      - run: deno task fmt:check
      - run: deno task check
      - run: deno task lint
  status-check:
    runs-on: ubuntu-latest
    needs:
      - check-actions
      - check-deno
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
